apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ingress-aws-controller
  namespace: kube-system
  labels:
    application: kube-ingress-aws-controller
    version: v0.6.8
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-ingress-aws-controller
  template:
    metadata:
      labels:
        application: kube-ingress-aws-controller
        version: v0.6.8
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        iam.amazonaws.com/role: "{{ .LocalID }}-app-ingr-ctrl"
    spec:
      priorityClassName: critical
      serviceAccountName: system
      containers:
      - name: controller
        image: registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:v0.6.8
        args:
        - -stack-termination-protection
        env:
        - name: AWS_REGION
          value: {{ .Region }}
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 25Mi
