apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-node-ready
  namespace: kube-system
  labels:
    application: kube-node-ready
    version: v0.0.1
spec:
  selector:
    matchLabels:
      application: kube-node-ready
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: kube-node-ready
        version: v0.0.1
      annotations:
        iam.amazonaws.com/role: "{{ .LocalID }}-kube-node-ready"
    spec:
      priorityClassName: system-node-critical
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: kube-node-ready
        image: registry.opensource.zalan.do/teapot/kube-node-ready:9799c3d
        args:
        - --master-lifecycle-hook={{ .Outputs.MasterAutoscalingLifecycleHook }}
        - --worker-lifecycle-hook={{ .Outputs.WorkerAutoscalingLifecycleHook }}
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 20Mi
