apiVersion: scheduling.k8s.io/v1alpha1
kind: PriorityClass
metadata:
  name: critical
value: 1000000
globalDefault: false
description: |
  This priority class is used for critical pods running in kube-system
  namespace.
